language: node_js
node_js:
  - "0.8"

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm install -g karma
  - npm install -g grunt-cli
  - ./nodeserver.sh > /dev/null &

script:
  - grunt
